export const bairros = [
    "Soledade",
    "Dom Luciano",
    "Santos Dumont",
    "Bugio",
    "Cidade Nova",
    "Santo Antônio",
    "Palestina",
    "Dezoito do Forte",
    "José Conrado de Araújo",
    "Olaria",
    "Jardim Centenário",
    "Capucho",
    "Novo Paraíso",
    "América",
    "Siqueira Campos",
    "Getúlio Vargas",
    "Centro",
    "Industrial",
    "Porto Dantas",
    "Jabutiana",
    "Coroa do Meio",
    "Farolândia",
    "Jardins",
    "São Conrado",
    "Cirurgia",
    "Inácio Barbosa",
    "Ponto Novo",
    "Aeroporto",
    "Aruanda",
    "Areia Branca",
    "Coroa do Meio",
    "Atalaia",
    "Gameleira",
    "Matapoã",
    "Mosqueiro",
    "Areia Branca",
    "Santa Maria",
    "Robalo",
    "São José dos Náufragos"
];